// LOGIN TYPES
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// LOAD USER TYPES
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// AUTHENTICATION TYPES
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

// LOGOUT TYPE
export const LOGOUT = "LOGOUT";

// CHANGE PASSWORD CONFIRMATION
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const PASSWORD_CONFIRMATION_SUCCESS = "PASSWORD_CONFIRMATION_SUCCESS";
export const PASSWORD_CONFIRMATION_FAIL = "PASSWORD_CONFIRMATION_FAIL";

// SIGNUP TYPES
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// ACTIVATION TYPES
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";

// ERROR
export const GET_ERROR = "GET_ERROR";
export const NO_ERROR = "NO_ERROR";
