# Generated by Django 3.1 on 2022-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
